# Generated by Django 3.2.12 on 2022-04-16 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220416_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileskill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
