# Generated by Django 3.2.12 on 2022-04-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profileskill_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profileskill',
            unique_together={('profile', 'skill')},
        ),
    ]
