# Generated by Django 3.2.12 on 2022-05-19 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileskill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileskills', to='accounts.profile'),
        ),
    ]
